package ee.cyber.cdoc2.auth;

import com.nimbusds.jose.JOSEException;
import com.nimbusds.jose.JWSAlgorithm;
import com.nimbusds.jose.crypto.ECDSASigner;
import com.nimbusds.jose.crypto.RSASSASigner;
import com.nimbusds.jose.jwk.ECKey;
import com.nimbusds.jose.jwk.JWK;
import com.nimbusds.jose.jwk.RSAKey;
import com.nimbusds.jose.util.X509CertUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.security.KeyStore;
import java.security.KeyStoreException;
import java.security.NoSuchAlgorithmException;
import java.security.cert.CertificateException;
import java.security.cert.CertificateFactory;
import java.security.cert.X509Certificate;
import java.text.ParseException;
import java.util.Set;
import java.util.List;
import com.nimbusds.jose.JWSHeader;
import com.nimbusds.jose.jca.JCAContext;
import com.nimbusds.jose.util.Base64URL;

import org.bouncycastle.asn1.pkcs.PrivateKeyInfo;
import org.bouncycastle.jce.provider.BouncyCastleProvider;
import org.bouncycastle.openssl.PEMKeyPair;
import org.bouncycastle.openssl.PEMParser;
import org.bouncycastle.openssl.jcajce.JcaPEMKeyConverter;

import java.io.StringReader;
import java.security.Security;
import java.security.Signature;

import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Input test data utility class.
 */
public final class TestData {

    //generated create-rsa-key-csr-crt-keystore.sh
    private static final String TEST_RSAKEY = """
        -----BEGIN RSA PRIVATE KEY-----
        MIIJKAIBAAKCAgEA1TyEtd/tUQsDtNfwy7l34SoUvBAnAXU8CFnXtF1e0+2Rb1hH
        Em/mRiwHvjmdVH6Gud03RVWi7Xc+pJLddM/EUxKdF5Rpe9exzNN7yTiOOIP3WcLS
        jwMdEOOUBE1aysUePcqQBB1Se/c2yiQuOBOe5OMzCZbvrv8JRW1T+FGmDVAtHTS0
        4Yv6gnudAd/BpCdbDdCzdaV2BgI5WME+IXnh7Nwg3GQuqNTwsZWNbfG+1gATLrfB
        aPWE5alQ1s2Kc+dbURJMA8JraKpVYx1P2h4jyCAQOe2Lza8d+/HPez2BiYFPJVO2
        ogLxLovcdfmhztTm2xDZBTzY0/c2XbjMpMERgIFIssH188FS0TXkWmwBG+cVhhl5
        SPY6YUEaRDa6lRe4940NGgZovlVcc0uLb+LVMcA9S6EE4egv50b+hFXQaejfuhnw
        5cnoCfvzb1dnY8dY7zVHMIDUyt0aAoU6OHRlSsBYTdaHYQuW0UxqzXZBzoGG6wZ6
        Wkycytg4DIJJyoI0Ces8MYHX7Kek8kcX0GsXGiO5HnmHGFkRgPwTOOhrPhcLalLO
        vFL+JtUotaot8wlay2JybaHbYtebjio6PkAGHiDOxMaU+8R25S7PhWPr8A9a+rft
        NXDQDZOSjZxFTtLjcXsXesZ7GU63arw073K7Kp3NoQ2r9oemq0ZawmDf9vMCAwEA
        AQKCAgA8utytE9Z582Id2jZpPyxGQ37eRNdnEeWEF1pYsxLz1sBJ7uFm/dmeeKHH
        6o7FZremLbu1Enuxl/mOU4mg4B9w7WcyNQGJ1Nd9l2m02Feg/uyucs8XDfL0QWyB
        gSpvf45qWMuFcHhyd+jxzzYeoG/rjk2V2Jfwxg/05vs4SMC7H++JVt6BMiWpjd0c
        kIaM4uyK1bqWsgYYFgARKBAy5oySserl+d5UFTlrykUaX/RS7HiKIKmD5BDye7Nb
        SfS5p9WZFFXz6CZBC+n/rXR1kYntUDxu0xmy/cHTZH4MAmtnJx3MargkEiRwdkLW
        kr8jsf0BvR2h4T97tveT37Lg5V+/LVI1FjB41HaJLtVXN6kjqulAVqsgx6L3Aee+
        BVIpppYEBiv9fal9etxRkV+H05teT4CX/zhHH13PKSLvIjKD9R9LR8PRDXA98Soy
        DU1BphBMubx5Z+J5XUAs4qi2rwwVV0AirlXZsyvAM9afj+AAT3eQUWFL4q+TGY69
        5DyWBnBdojMp9xot6q5TOx+0GL9MKIob062NlaGApdfHRzSg8fVg8geawam2p0VD
        F7hLaxzFKOlrfv3FZj10lHH/o1JbiPoJRBrfe/PT66LbR1H/3F/89T2fQS60GCIG
        Wv+RcMV9usrLmN5E8LbA8yue8Jg23/aPLPTeOmMMoF5oYtYTsQKCAQEA9a3kVljZ
        rYYcMJZF+NLstRF3gaNq4n8g8i+k73nEYy3Y8h9DfpPZ7IiHz5yQwoN9hVyDNUuV
        7Cio/3kpc0TiP7swQ+8RBtgot/hhkHfR7xz//PMRUkFMS0OvlbnjmnUavhM3hJff
        SC0Zfq2YZ2/X6XE8arcslwmybu7JeNdN2n9W1wuGYTALP3EZvHTdq2g3rCoA4btq
        qRUiHabpwDyRCtC16QMZY/7lHB/u89IhZa0E8o7ryJHvuNNYYndbeC8znv44jigx
        wTNTkW2m/0w1CAb+lYPSnCssJfvboXvVrvDWBrvffybX3kqUpF1C+lIdtOxOD2Mx
        +XiA0+Er/oGZiwKCAQEA3jG56QVI3KF+kKk/Bdlj/FWepfE5Sde3PLuwT+e4PX9U
        Xg82ZJ/IqH97NpKJOV/tmo8LmheZl3sXSXQY4lSVXhMEqFVK4F43vHu3TsUe8gig
        q7po/m+1DSxjDbVWUnksOAOxTIK6i5Wry2VophgypdtW1/qSZSP5qMcG5QopxZ0w
        rYE+rOUXsegHGXwFRbEmJD9T07amJDI2vwlBDsFK7sOSuO0o/D1luenJs9ttFdub
        0El9e0p1kz4R5uM2UUFZsbOMwN1tMEYipmH6yCBMGy0t3RzqUKyLM27p3rni6OdB
        9PmFh8s6AW4BuSSMMd6O+LAt+1W2c801714v7RE1OQKCAQBEzr4b3Oiia+QrS3sv
        dEutbsXsvgsqgnaEvglQtObm7ClNrqnlop0vXRHEeNImWFNobX+mBpRnvv+OBa4x
        RYKkXNXowOUg6JuG4v7YSma2tIWRn7YjNnyau8tKgPSZBuFFiPZMoYh8m3z/eLkt
        hyqOjBNixAiuCJ476Y7t1EdOwcldkzHAuIb97rxJhuWqoxasllsG3cnCr1ONwHjJ
        SW1J/ShlqWOMGRCr7tmq2hhWdL3k/VhWJWFhf3fKpCkvIPExP3wxfFprBOgL3A0g
        hYR4yhS1ZWUwLftAbCiYMqmnRHZ9DlNLNmLRNEwrOJ+Qoj0FtgUq1BpkB3b1YKRE
        tKF/AoIBAFfhsRdyKKRjF40d87hbiEloj+wwYalMMcRKs+yWyO9B6ludhrT74cCL
        U299O9s+jtq/0yXqSax5WfeKfMEgFUf1G7V8rrXZbhAVmqYEHz45nVruytI/2otQ
        UAk+/Np35L5u73REjIXi9+TlwiNXlMi23T1ldPud5AQWXCrA/06S4ortgJ2fquSJ
        0i0JOYicDWruxTgKmOHeHnsmrN2qI/oVznVoD/rcSdzjlAyYMCgiCRmzx3a5N5G6
        ThhVK8mtoE1Bp90sdyBNzSyjui3nYFKrZuV6p06rQA9iwgt+2DmoJhU/j8nq3pFs
        MjBJPU4IKeJAxJ8RAq4Ar2FyjmAkmzkCggEBAOsLsYQt+O7NqreRr6YTvWC3cZJK
        0K3+azexC5DHOIkL/vrWFQrh04zAUfa6eSHCCICKCdTvZGaAfmgddPD3AEho62R1
        Sju+OFabLhyogR7IcCogY072MDRBo8uMoQomgDI3tOq9fQjIqW7ngA9ZzGs+rI6n
        aOd46ydm4M000Ng95JCOsaa2nLAVC6EhEvi88G4hdRvBS2g0ftuYFnbTYKsv6IWq
        3sjpa4gfbsXoa6mTbEKMd6wTfZilkhu5x/LxXhRBLuZvwj/mtQQwK/Jl6e9Wvnlv
        yS//HS9wVyAOtzIHDyLGRZfoWzm8WinYKg9gFBf4keqhHEJMKQfMxeSMcLw=
        -----END RSA PRIVATE KEY-----
        """;

    // generated create-rsa-key-csr-crt-keystore.sh
    // signing cert sk-ca.localhost.crt must be in server sid trust store
    // mock service certificate
    public static final String TEST_RSA_CERT_PEM = "-----BEGIN CERTIFICATE-----"
        + """
        MIIDuTCCA2CgAwIBAgIUTL1AousETAVENwEl62mocPaUfZQwCgYIKoZIzj0EAwQw
        TDELMAkGA1UEBhMCRUUxEDAOBgNVBAcMB1RhbGxpbm4xETAPBgNVBAoMCHNrLWxv
        Y2FsMRgwFgYDVQQDDA9zay1jYS5sb2NhbGhvc3QwHhcNMjQxMTI1MjAwMDQ5WhcN
        MjUxMTI1MjAwMDQ5WjBjMRowGAYDVQQFExFQTk9FRS0zMDMwMzAzOTkxNDELMAkG
        A1UEKgwCT0sxEzARBgNVBAQMClRFU1ROVU1CRVIxFjAUBgNVBAMMDVRFU1ROVU1C
        RVIsT0sxCzAJBgNVBAYTAkVFMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKC
        AgEA1TyEtd/tUQsDtNfwy7l34SoUvBAnAXU8CFnXtF1e0+2Rb1hHEm/mRiwHvjmd
        VH6Gud03RVWi7Xc+pJLddM/EUxKdF5Rpe9exzNN7yTiOOIP3WcLSjwMdEOOUBE1a
        ysUePcqQBB1Se/c2yiQuOBOe5OMzCZbvrv8JRW1T+FGmDVAtHTS04Yv6gnudAd/B
        pCdbDdCzdaV2BgI5WME+IXnh7Nwg3GQuqNTwsZWNbfG+1gATLrfBaPWE5alQ1s2K
        c+dbURJMA8JraKpVYx1P2h4jyCAQOe2Lza8d+/HPez2BiYFPJVO2ogLxLovcdfmh
        ztTm2xDZBTzY0/c2XbjMpMERgIFIssH188FS0TXkWmwBG+cVhhl5SPY6YUEaRDa6
        lRe4940NGgZovlVcc0uLb+LVMcA9S6EE4egv50b+hFXQaejfuhnw5cnoCfvzb1dn
        Y8dY7zVHMIDUyt0aAoU6OHRlSsBYTdaHYQuW0UxqzXZBzoGG6wZ6Wkycytg4DIJJ
        yoI0Ces8MYHX7Kek8kcX0GsXGiO5HnmHGFkRgPwTOOhrPhcLalLOvFL+JtUotaot
        8wlay2JybaHbYtebjio6PkAGHiDOxMaU+8R25S7PhWPr8A9a+rftNXDQDZOSjZxF
        TtLjcXsXesZ7GU63arw073K7Kp3NoQ2r9oemq0ZawmDf9vMCAwEAAaM+MDwwHwYD
        VR0jBBgwFoAUbs3btcBBYBn+RwvDkSG9Gz2Sxl8wDAYDVR0TAQH/BAIwADALBgNV
        HQ8EBAMCBaAwCgYIKoZIzj0EAwQDRwAwRAIgJsR3WD6ZAIS5+K3YZ822QjmZYHOT
        oeW6Qz1MZFgQba8CIBCrja2kNYPtyJmJF/sespAVdz7eYHxgNUkM4cqEWFkz
        """.replaceAll("\\s", "")
        + "-----END CERTIFICATE-----"; //remove all whitespace

    // SK-CA.localhost.crt
    public static final String TEST_RSA_CERT_ISSUER_PEM = """
        -----BEGIN CERTIFICATE-----
        MIIB7jCCAZOgAwIBAgIUc3AeVxEYSTyVlAXpkFxs/G3OKD4wCgYIKoZIzj0EAwQw
        TDELMAkGA1UEBhMCRUUxEDAOBgNVBAcMB1RhbGxpbm4xETAPBgNVBAoMCHNrLWxv
        Y2FsMRgwFgYDVQQDDA9zay1jYS5sb2NhbGhvc3QwHhcNMjQxMTA0MTM0MjEwWhcN
        MjUxMTA0MTM0MjEwWjBMMQswCQYDVQQGEwJFRTEQMA4GA1UEBwwHVGFsbGlubjER
        MA8GA1UECgwIc2stbG9jYWwxGDAWBgNVBAMMD3NrLWNhLmxvY2FsaG9zdDBZMBMG
        ByqGSM49AgEGCCqGSM49AwEHA0IABIIMkZNhqQizD1kHUcyFEKGA8b+SXua07Fvl
        O67ZyCNq+uQggVh0szDURFDzaNDFQDY0R5ac9mL2+4NxPyCmihijUzBRMB0GA1Ud
        DgQWBBRuzdu1wEFgGf5HC8ORIb0bPZLGXzAfBgNVHSMEGDAWgBRuzdu1wEFgGf5H
        C8ORIb0bPZLGXzAPBgNVHRMBAf8EBTADAQH/MAoGCCqGSM49BAMEA0kAMEYCIQD0
        Wb6Dy2G+NPFaKQQ6SpJl5QNMJ0mMagbSz48Sky8DpAIhAOvVu2zPH4aaqiZhZCq7
        6ReVJoevfe0/H0JM7AciG+1P
        -----END CERTIFICATE-----""";

    // 30303039914 ECDSA certificate
    private static final String TEST_ECDSA_CERT_PEM = """
        -----BEGIN CERTIFICATE-----
        MIICDzCCAbWgAwIBAgIUVn26RKn5tb6rOhO4sMrInr8UgxEwCgYIKoZIzj0EAwQw
        TTELMAkGA1UEBhMCRUUxEDAOBgNVBAcMB1RhbGxpbm4xDzANBgNVBAoMBi1sb2Nh
        bDEbMBkGA1UEAwwSY3liZXItY2EubG9jYWxob3N0MB4XDTI1MDExMzE2MDE1OFoX
        DTI2MDExMzE2MDE1OFowYzEaMBgGA1UEBRMRUE5PRUUtMzAzMDMwMzk5MTQxCzAJ
        BgNVBCoMAk9LMRMwEQYDVQQEDApURVNUTlVNQkVSMRYwFAYDVQQDDA1URVNUTlVN
        QkVSLE9LMQswCQYDVQQGEwJFRTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABAWe
        VJrrXvoxM0smdRMl6pfmRLeHFVl9cBu9V2tLyTPVbWGM9KTWMtTK+Z8cuJP/9Qwf
        VYbyildK3Ljh0e3DoDyjXTBbMB8GA1UdIwQYMBaAFMOo1Ks+YOgIJxdsDy4nChTP
        jAlvMAwGA1UdEwEB/wQCMAAwCwYDVR0PBAQDAgWgMB0GA1UdDgQWBBRLVYFQ5JNE
        dGE3HjPOHWGWNebXmTAKBggqhkjOPQQDBANIADBFAiEA32rCmKZd5uho96r3zhWb
        e6SuLRYHAsuUqj5IcMx8cJ0CIA8ntNP2P2oAQRf0wmypbvzyirYtu6Im1hf1vh/Y
        BX2H
        -----END CERTIFICATE-----""";

    // 30303039914 ECDSA certificate private key
    private static final String TEST_ECDSA_KEY = """
        -----BEGIN EC PRIVATE KEY-----
        MHcCAQEEIBcKDOTuvQgeXk/Ba+B63t1oz0bTJ8hzY7y1s9HSsavmoAoGCCqGSM49
        AwEHoUQDQgAEBZ5Umute+jEzSyZ1EyXql+ZEt4cVWX1wG71Xa0vJM9VtYYz0pNYy
        1Mr5nxy4k//1DB9VhvKKV0rcuOHR7cOgPA==
        -----END EC PRIVATE KEY-----""";

    // ECDSA cyber-ca.localhost.crt
    public static final String TEST_ECDSA_CERT_ISSUER_PEM = """
        -----BEGIN CERTIFICATE-----
        MIIB8DCCAZWgAwIBAgIUH+YPt2fcRJtQnv0S0qaepo11SnUwCgYIKoZIzj0EAwQw
        TTELMAkGA1UEBhMCRUUxEDAOBgNVBAcMB1RhbGxpbm4xDzANBgNVBAoMBi1sb2Nh
        bDEbMBkGA1UEAwwSY3liZXItY2EubG9jYWxob3N0MB4XDTI1MDExMzE1NTc0MloX
        DTI2MDExMzE1NTc0MlowTTELMAkGA1UEBhMCRUUxEDAOBgNVBAcMB1RhbGxpbm4x
        DzANBgNVBAoMBi1sb2NhbDEbMBkGA1UEAwwSY3liZXItY2EubG9jYWxob3N0MFkw
        EwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAERSZfTmk6OZhO55tULRJMn4ALjblWXoxI
        tbo+mj0isO8lO8kbdwAu8b3ndJ6OJrdFxs9znhEbwtwOk7TB8fxNc6NTMFEwHQYD
        VR0OBBYEFMOo1Ks+YOgIJxdsDy4nChTPjAlvMB8GA1UdIwQYMBaAFMOo1Ks+YOgI
        JxdsDy4nChTPjAlvMA8GA1UdEwEB/wQFMAMBAf8wCgYIKoZIzj0EAwQDSQAwRgIh
        AMNstkihBiWmsQnfDnxuu9yPSG0XQLxjlf6seUh7Wh5RAiEA/y9FA8R1kuelLxWs
        Yro9lhiEr72sQG//4CDRjTxuT7E=
        -----END CERTIFICATE-----""";

    // CA certificate for Smart-id test account PNOEE-30303039914
    // https://github.com/SK-EID/smart-id-java-client/blob/master/README.md
    public static final String TEST_PEM_30303039914 = """
        -----BEGIN CERTIFICATE-----
        MIIIIjCCBgqgAwIBAgIQUJQ/xtShZhZmgogesEbsGzANBgkqhkiG9w0BAQsFADBoM
        QswCQYDVQQGEwJFRTEiMCAGA1UECgwZQVMgU2VydGlmaXRzZWVyaW1pc2tlc2t1cz
        EXMBUGA1UEYQwOTlRSRUUtMTA3NDcwMTMxHDAaBgNVBAMME1RFU1Qgb2YgRUlELVN
        LIDIwMTYwIBcNMjQwNzAxMTA0MjM4WhgPMjAzMDEyMTcyMzU5NTlaMGMxCzAJBgNV
        BAYTAkVFMRYwFAYDVQQDDA1URVNUTlVNQkVSLE9LMRMwEQYDVQQEDApURVNUTlVNQ
        kVSMQswCQYDVQQqDAJPSzEaMBgGA1UEBRMRUE5PRUUtMzAzMDMwMzk5MTQwggMiMA
        0GCSqGSIb3DQEBAQUAA4IDDwAwggMKAoIDAQCo+o1jtKxkNWHvVBRA8Bmh08dSJxh
        L/Kzmn7WS2u6vyozbF6M3f1lpXZXqXqittSmiz72UVj02jtGeu9Hajt8tzR6B4D+D
        wWuLCvTawqc+FSjFQiEB+wHIb4DrKF4t42Aazy5mlrEy+yMGBe0ygMLd6GJmkFw1p
        zINq8vu6sEY25u6YCPnBLhRRT3LhGgJCqWQvdsN3XCV8aBwDK6IVox4MhIWgKgDF/
        dh9XW60MMiW8VYwWC7ONa3LTqXJRuUhjFxmD29Qqj81k8ZGWn79QJzTWzlh4NoDQT
        8w+8ZIOnyNBAxQ+Ay7iFR4SngQYUyHBWQspHKpG0dhKtzh3zELIko8sxnBZ9HNkwn
        IYe/CvJIlqARpSUHY/Cxo8X5upwrfkhBUmPuDDgS14ci4sFBiW2YbzzWWtxbEwiRk
        dqmA1NxoTJybA9Frj6NIjC4Zkk+tL/N8Xdblfn8kBKs+cAjk4ssQPQruSesyvzs4E
        GNgAk9PX2oeelGTt02AZiVkIpUha8VgDrRUNYyFZc3E3Z3Ph1aOCEQMMPDATaRps3
        iHw/waHIpziHzFAncnUXQDUMLr6tiq+mOlxYCi8+NEzrwT2GOixSIuvZK5HzcJTBY
        z35+ESLGjxnUjbssfra9RAvyaeE1EDfAOrJNtBHPWP4GxcayCcCuVBK2zuzydhY6K
        t8ukXh5MIM08GRGHqj8gbBMOW6zEb3OVNSfyi1xF8MYATKnM1XjSYN49My0BPkJ01
        xCwFzC2HGXUTyb8ksmHtrC8+MrGLus3M3mKFvKA9VatSeQZ8ILR6WeA54A+GMQeJu
        V54ZHZtD2085Vj7R+IjR+3jakXBvZhVoSTLT7TIIa0U6L46jUIHee/mbf5RJxesZz
        kP5zA81csYyLlzzNzFah1ff7MxDBi0v/UyJ9ngFCeLt7HewtlC8+HRbgSdk+57Kga
        FIgVFKhv34Hz1Wfh3ze1Rld3r1Dx6so4h4CZOHnUN+hprosI4t1y8jorCBF2GUDbI
        qmBCx7DgqT6aE5UcMcXd8CAwEAAaOCAckwggHFMAkGA1UdEwQCMAAwDgYDVR0PAQH
        /BAQDAgSwMHkGA1UdIARyMHAwZAYKKwYBBAHOHwMRAjBWMFQGCCsGAQUFBwIBFkho
        dHRwczovL3d3dy5za2lkc29sdXRpb25zLmV1L3Jlc291cmNlcy9jZXJ0aWZpY2F0a
        W9uLXByYWN0aWNlLXN0YXRlbWVudC8wCAYGBACPegECMB0GA1UdDgQWBBQUFyCLUa
        wSl3KCp22kZI88UhtHvTAfBgNVHSMEGDAWgBSusOrhNvgmq6XMC2ZV/jodAr8StDA
        TBgNVHSUEDDAKBggrBgEFBQcDAjB8BggrBgEFBQcBAQRwMG4wKQYIKwYBBQUHMAGG
        HWh0dHA6Ly9haWEuZGVtby5zay5lZS9laWQyMDE2MEEGCCsGAQUFBzAChjVodHRwO
        i8vc2suZWUvdXBsb2FkL2ZpbGVzL1RFU1Rfb2ZfRUlELVNLXzIwMTYuZGVyLmNydD
        AwBgNVHREEKTAnpCUwIzEhMB8GA1UEAwwYUE5PRUUtMzAzMDMwMzk5MTQtTU9DSy1
        RMCgGA1UdCQQhMB8wHQYIKwYBBQUHCQExERgPMTkwMzAzMDMxMjAwMDBaMA0GCSqG
        SIb3DQEBCwUAA4ICAQCqlSMpTx+/nwfI5eEislq9rce9eOY/9uA0b3Pi7cn6h7jdF
        es1HIlFDSUjA4DxiSWSMD0XX1MXe7J7xx/AlhwFI1WKKq3eLx4wE8sjOaacHnwV/J
        STf6iSYjAB4MRT2iJmvopgpWHS6cAQfbG7qHE19qsTvG7Ndw7pW2uhsqzeV5/hcCf
        10xxnGOMYYBtU7TheKRQtkeBiPJsv4HuIFVV0pGBnrvpqj56Q+TBD9/8bAwtmEMSc
        QUVDduXPc+uIJJoZfLlUdUwIIfhhMEjSRGnaK4H0laaFHa05+KkFtHzc/iYEGwJQb
        iKvUn35/liWbcJ7nr8uCQSuV4PHMjZ2BEVtZ6Qj58L/wSSidb4qNkSb9BtlK+wwND
        jbqysJtQCAKP7SSNuYcEAWlmvtHmpHlS3tVb7xjko/a7zqiakjCXE5gIFUmtZJFbG
        5dO/0VkT5zdrBZJoq+4DkvYSVGVDE/AtKC86YZ6d1DY2jIT0c9BlbFp40A4Xkjjjf
        5/BsRlWFAs8Ip0Y/evG68gQBATJ2g3vAbPwxvNX2x3tKGNg+aDBYMGM76rRrtLhRq
        PIE4Ygv8x/s7JoBxy1qCzuwu/KmB7puXf/y/BBdcwRHIiBq2XQTfEW3ZJJ0J5+Kq4
        8keAT4uOWoJiPLVTHwUP/UBhwOSa4nSOTAfdBXG4NqMknYwvAE9g==
        -----END CERTIFICATE-----""";

    // Issuer cert TEST of EID-SK 2016.pem for PNOEE-30303039914
    public static final String TEST_30303039914_ISSUER_PEM = """
        -----BEGIN CERTIFICATE-----
        MIIHCTCCBfGgAwIBAgIQVrOxHLphb7pfUJLPiYJRMzANBgkqhkiG9w0BAQwFADB9
        MQswCQYDVQQGEwJFRTEiMCAGA1UECgwZQVMgU2VydGlmaXRzZWVyaW1pc2tlc2t1
        czEwMC4GA1UEAwwnVEVTVCBvZiBFRSBDZXJ0aWZpY2F0aW9uIENlbnRyZSBSb290
        IENBMRgwFgYJKoZIhvcNAQkBFglwa2lAc2suZWUwHhcNMjAwOTAzMDY1MzAzWhcN
        MzAxMjE3MjE1OTU5WjBoMQswCQYDVQQGEwJFRTEiMCAGA1UECgwZQVMgU2VydGlm
        aXRzZWVyaW1pc2tlc2t1czEXMBUGA1UEYQwOTlRSRUUtMTA3NDcwMTMxHDAaBgNV
        BAMME1RFU1Qgb2YgRUlELVNLIDIwMTYwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAw
        ggIKAoICAQDqyjgcqyaktULCg+LV4apGWnzzHebH8XpuolWzAAByqbzrOCGtqF3U
        rydhY6zJebM3k+JaR8s3xAszt58e6b0Syh7n4upTMDBo7UiOgyvAYh/c+y5vpDS7
        pzRXSIq9IT4o42yJI4PYsH2nkk/RYuedNi7Cu3boSrgpx+ztLjK0vzMpyeErQDRm
        Nd19hbz1uKpK7W8LJoXTdAba6O9juv9zvtL256v8glrXEKwRr9/vFxAXQqh+Uv0b
        dBLoCl+FJVcuZdEFHPCK4xrXTLK/Sg7b5lcJXn12CqC6pAu4LjBjlDX+mOAGBrD6
        n2OHRtzeWDaeRRwy+yDvd4e06UVd4Mkd/C4ibDx5OZxEuZnT5DbhJAsoNMxCiO7i
        eC1LgW482T6doD+zzfCKovRj+1djQs/L1FTd1qR73LbH9AzL2XVeacai2OaI8n4T
        LFOGjHBkkAPRCvBEtztcwStQ1vm7Y20I1BVtUiMApAdsqHxcYHvr782Rm77dlBjh
        PKAC/PyczcYvRW40wG8nKxloBDENLDNXynPjrL6GksvZt2UBqYdPnW7KLkKZd5KS
        b4wzM8cZKzKsXYZVTK3iyhgjDMSTABkBMFUuT/dzZ5s/FG5JnqJlCa9zawaOPlfS
        +UuCsdb07w9Ke9sUWBcn4nyzo7PKrO5Ud8oZHAT0CO/BEasb99RVgwIDAQABo4IC
        mDCCApQwHwYDVR0jBBgwFoAUtTQKnaUvEMXnIQ6+xLFlRxsDdv4wHQYDVR0OBBYE
        FK6w6uE2+CarpcwLZlX+Oh0CvxK0MA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8E
        CDAGAQH/AgEAMIHEBgNVHSAEgbwwgbkwPAYHBACL7EABAjAxMC8GCCsGAQUFBwIB
        FiNodHRwczovL3d3dy5zay5lZS9yZXBvc2l0b29yaXVtL0NQUzA8BgcEAIvsQAEA
        MDEwLwYIKwYBBQUHAgEWI2h0dHBzOi8vd3d3LnNrLmVlL3JlcG9zaXRvb3JpdW0v
        Q1BTMDsGBgQAj3oBAjAxMC8GCCsGAQUFBwIBFiNodHRwczovL3d3dy5zay5lZS9y
        ZXBvc2l0b29yaXVtL0NQUzAnBgNVHSUEIDAeBggrBgEFBQcDCQYIKwYBBQUHAwIG
        CCsGAQUFBwMEMIGOBggrBgEFBQcBAQSBgTB/MCIGCCsGAQUFBzABhhZodHRwOi8v
        ZGVtby5zay5lZS9vY3NwMFkGCCsGAQUFBzAChk1odHRwOi8vd3d3LnNrLmVlL3Vw
        bG9hZC9maWxlcy9URVNUX29mX0VFX0NlcnRpZmljYXRpb25fQ2VudHJlX1Jvb3Rf
        Q0EuZGVyLmNydDBBBgNVHR4EOjA4oTYwBIICIiIwCocIAAAAAAAAAAAwIocgAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwJQYIKwYBBQUHAQMEGTAXMBUG
        CCsGAQUFBwsCMAkGBwQAi+xJAQEwQwYDVR0fBDwwOjA4oDagNIYyaHR0cHM6Ly93
        d3cuc2suZWUvcmVwb3NpdG9yeS9jcmxzL3Rlc3RfZWVjY3JjYS5jcmwwDQYJKoZI
        hvcNAQEMBQADggEBACawLCQnjAOtDCaNejt1AqMVc8IwWy03TAAvceJd7rRSG9w2
        Q69OxVMVhUpQ4+K+M+Fqtpkq5IWO9GFXYeYL5JwiL4rjKPk1MIunM4ZKr6f+NQBy
        4A4oHL0ArF4QoQZuYnUS/jesjQs2HXEthcLjdSkFyaoAyfPH50c0WTMDhZj8eEIK
        NWPEqGmGZPkAc4+ivFdl7zEC6ZaaJ6NdtihQKdFcisgv3Uyc4kuzmHK/6OtNAXpg
        qaiLyf4L3ThQ2KA+EuDp6B97rOfV4JWC265HkAwxKd9/3fk7pwnfyMxIonW5MGcN
        nrlYjNXNft5cr9xu2A8mPXh2ArMiZ1yif5NDvHI=
        -----END CERTIFICATE-----""";

    // Root cert TEST_of_EE_Certification_Centre_Root_CA.pem.crt for 'TEST of EID-SK 2016.pem'
    public static final String TEST_30303039914_ISSUER_ROOT_PEM = """
        -----BEGIN CERTIFICATE-----
        MIIEEzCCAvugAwIBAgIQc/jtqiMEFERMtVvsSsH7sjANBgkqhkiG9w0BAQUFADB9
        MQswCQYDVQQGEwJFRTEiMCAGA1UECgwZQVMgU2VydGlmaXRzZWVyaW1pc2tlc2t1
        czEwMC4GA1UEAwwnVEVTVCBvZiBFRSBDZXJ0aWZpY2F0aW9uIENlbnRyZSBSb290
        IENBMRgwFgYJKoZIhvcNAQkBFglwa2lAc2suZWUwIhgPMjAxMDEwMDcxMjM0NTZa
        GA8yMDMwMTIxNzIzNTk1OVowfTELMAkGA1UEBhMCRUUxIjAgBgNVBAoMGUFTIFNl
        cnRpZml0c2VlcmltaXNrZXNrdXMxMDAuBgNVBAMMJ1RFU1Qgb2YgRUUgQ2VydGlm
        aWNhdGlvbiBDZW50cmUgUm9vdCBDQTEYMBYGCSqGSIb3DQEJARYJcGtpQHNrLmVl
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1gGpqCtDmNNEHUjC8LXq
        xRdC1kpjDgkzOTxQynzDxw/xCjy5hhyG3xX4RPrW9Z6k5ZNTNS+xzrZgQ9m5U6uM
        ywYpx3F3DVgbdQLd8DsLmuVOz02k/TwoRt1uP6xtV9qG0HsGvN81q3HvPR/zKtA7
        MmNZuwuDFQwsguKgDR2Jfk44eKmLfyzvh+Xe6Cr5+zRnsVYwMA9bgBaOZMv1TwTT
        VNi9H1ltK32Z+IhUX8W5f2qVP33R1wWCKapK1qTX/baXFsBJj++F8I8R6+gSyC3D
        kV5N/pOlWPzZYx+kHRkRe/oddURA9InJwojbnsH+zJOa2VrNKakNv2HnuYCIonzu
        pwIDAQABo4GKMIGHMA8GA1UdEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgEGMB0G
        A1UdDgQWBBS1NAqdpS8QxechDr7EsWVHGwN2/jBFBgNVHSUEPjA8BggrBgEFBQcD
        AgYIKwYBBQUHAwEGCCsGAQUFBwMDBggrBgEFBQcDBAYIKwYBBQUHAwgGCCsGAQUF
        BwMJMA0GCSqGSIb3DQEBBQUAA4IBAQAj72VtxIw6p5lqeNmWoQ48j8HnUBM+6mI0
        I+VkQr0EfQhfmQ5KFaZwnIqxWrEPaxRjYwV0xKa1AixVpFOb1j+XuVmgf7khxXTy
        Bmd8JRLwl7teCkD1SDnU/yHmwY7MV9FbFBd+5XK4teHVvEVRsJ1oFwgcxVhyoviR
        SnbIPaOvk+0nxKClrlS6NW5TWZ+yG55z8OCESHaL6JcimkLFjRjSsQDWIEtDvP4S
        tH3vIMUPPiKdiNkGjVLSdChwkW3z+m0EvAjyD9rnGCmjeEm5diLFu7VMNVqupsbZ
        SfDzzBLc5+6TqgQTOG7GaZk2diMkn03iLdHGFrh8ML+mXG9SjEPI
        -----END CERTIFICATE-----""";

    // Prototype ML-DSA private key PEM
    private static final String TEST_MLDSA_KEY = """
    -----BEGIN PRIVATE KEY-----
    MIIP/gIBADALBglghkgBZQMEAxIEgg/qMIIP5gQgxdu4CJJafAImS84OfbRKvimx
    80HnxDc8oRF8qCUu1xUEgg/AFVc/zCncqzCsXQI3dTrsA/PScu7RXXH2XW8nPIJO
    LKkdLUxGIYpjHHfnsmhPxvydQtk3Qfr0IRf0NQY82vDfp7IND258ZWekTWTkuWjB
    ePBewdE52T63p70x/imTidi6Aypq99aLmvMXirLDvTzuHUQZlpRoI1SFTrtbGMaj
    pk6DNgVVAyQSJEeFR3ZCcziFMjhxhCZzIFZABEEydzI1YDMmNWeGg3BRV2hDQoAm
    FQg0EXUCgTd0Z0cIVUNEBEB3cGMFAIZBdnUBRiR1IDAnNVFIU3CFRnZBZxdiExB2
    NSeGZlOGIzIBZhZzhHdnhWUiRWhVdRiBZRYFV2JDZRVwdnUkViIoiIVnUAFIImBy
    YlADRAUnQCYSEXNYFDF4UVYFB2NYUmZkdTATYiNYcHY2gUdSGENkIEQAFTdAExFY
    Y1AEaAhwM4ZzRQQ0VHVnFGhGAyMhdhYjJQF1dECDdAIXYCg0MgIiIAZ0KIM3JGEB
    h4EQQYNBZhJzMDMGJnVBh4UgZxJSIHYBcYVFBmVxdwGHUDCDdGFFhVhlgoNmBXVS
    M2VAAIcxRoElB4Z1USFUFAgiR0QVQFgVUTJAA2YlBQIoEgNzhSVkcVMHJmV3VkiF
    REhGJmMEhxVzZVCEAkNjAUEUF0gjQ3QhZ3QmdjBUQjQShCRVdBMnGAYQVHIUZ1Um
    MVGAFEeCMlAIZDBQgIZRIFI0gnMoVmdhUCUhdGiIUiM2OFiDGIERIDQIVhYXUIiG
    SBYjKIUSQ1AEF1Z0NUCANjZkhgYlcIJ4dVEoI4BzaGg4c0Z1c0dScjhyISeDhFIy
    OIJnMAREV1c2ATVABndUgWZWcBR3YwA4UEF0I0NzF0chZ3IQEwdoNBMTFQNxiDYI
    M1gGh1gRBFcmMnYBUjBGgGE2MDFVQ2RSFAVyBoEQUHUAUnI0cndxIIg0ECQkKDNw
    UDMAcwUwdTM0VAAYhQIlYjAkKGhQVXYxYQdSBQM0VxZXAUU1VYZYNVMCYoEWgoFI
    UVMVM0JlUweEAFaBIIQSUgcgEENWZGQABWRVInYXdHiDYSUHN0gzAyRWMVADZnEG
    MUJ0ByczCDY3YoI1SCUXUgNgeHRgZGWAEWIRglQmATRmBSEiFlhEFUVVYTMWNoU4
    hUdiFiEAEHdTc1d4c3WDAQdVOGUmYlaFQkE0R4JXQ3MxdDAlIzBoF3YnchVhVBUj
    VwFSQRGAZyBDVAFyM2cIMXCIBBJRgFciIGCDUIJBhYQhV3AxEYIRZxZlhAg3iIgV
    BkYYhTcFJUdRZScnYCg1AkIhVnY1FgBkcQZQhjOHIQgFRGSEQoUASHBRU2A0dANE
    MVdxQlgDNVA4gWAEBRASdyBQJmAUcTQXcFNgBSFWMFckZjNYOHdRdXeBcIgCBVeD
    Y4N4VXMIh4QIJQIhIkNBMmEHgTZWFRZWJmNRNDJnhBVEUCckUFVUIHMzZ4AIGDdQ
    doJ2JGAWeGcgAUgjiEM4KBdlhxQXVIgDRSRCcXJRZnNBeBAngjVHdmeHZhJyBnMW
    hCRlAkZ4aBAAMSeHGBQFZWAjRAdHgnAEUgBFJjciNnhwR4AjU3NVBXdCRXdCMXhT
    dXQlByBHQiInYHZEGHJRJAcWFDBxInhBFgA0FhgCd2FTM1gVRSEjU1KBA2Q0YScW
    cYCEgjZSQ4F1gwBzJEAEOFVDBhaIZ0MHUjNYUBNTRYISKGdwcmCFAWMDczZjJFFB
    eIEoJXFARIgSBHQXZ0IkUHFVElN2RIdBeEeESEGFVgYHVRNXYXRCcRMjc2gTAyJB
    Fzg2c2UXUXE4IyEiJhEUUiEyYnFQQWYGQWcUEHABQzZhiFB2UoBXdFFAcxMRJRIV
    EwYiIBZoMEMgEmZFAhcXUlNDhAhBUkeIhlA3ZCKENVEmNTISImIiRAMWhVaIYCUG
    cjSCRoSFdQdyUUBgAYYUgTAhMYFTSHUkIWIiR0JlETBHB1ZBM0hoJzAmNnUEJRQU
    dnJVdxInMmVQEgRgMjg4Z4J1FnUzMWghQwV1coIzhCESOIZBOBVkdTgTYoN4JQRk
    EgNYhzgHUDZRVCdEAycjVXg0OA3oTU1c/mpooSClaOO7zTLKTzOuweJUIO31jXJD
    HsEO+LYvPfzfWc+9at+6vOmUh99TawEj4jS7OQjUjD7l11cMqZb/TypKpcgf1hYi
    G8uvn6A8JRDSP/Dcs6rW4Uzluw+V9TYqFxIsnTAz7ytW/eUvTDs9sGOC8txNzeKg
    dJ9QpT1JshJBq0anYg/bqV/fGVwGKTtctTD3NlmwQO7xm3n/IIzZAGgkeHWSC24i
    EcMZ52UEoPRUOkjQgH++wIcprsDn7GjPcWnhbatcaAQd4rcLcgrjuo3gTKpJ1kXy
    nL67wZvRlL0dacHJjbVjhVTrgsXOqSxKwz35LZcilTWszFAVU2cKtBif9fDnocKt
    DxjhnlF4HCnB315URr1sOY6MR+NwQNRYpCqJdzQ7bFG13WYe13C2nNkTvuN++H0y
    V/OI59nZ+quJ1MCVrumwM9b4baflxy3bx9jbrv2V/mOxEcC6YUe3LHJ6ozHlyVRx
    T7T2Enkh9pMexWBAAwa7ct3x+KJbcJxLQkovtTIGERm6EqV9e4sngvsyi2MIicg7
    oKeJ02fQxCa+v7EWGnmib1GH2oy8t+HN7Kr1sNHobQCUyZ5zB0yWtQB2BSzVT8rr
    jKpdUxxAmTwLybdcR3PgVVJvPel6xZyoieTk8ptWnei3JCeg9lgc0B8JX//UhDTm
    e2eIOvdVW88SgetYWcTtvyRGwLCfUlAV55CPXxoUIdchghM1QzRxSWUG/Rkeo195
    wGS5adSGyYZu9naOrzo0li/WeHl4Lvgf7QGiHrsX1PGgv1pZE73V6TS49mCgzKnZ
    +KilnuhGBLrtGrKkHMmeJDSVJ1a5p5J/vX5jZnMgCKk34waRGzL/bpJXN5F104X2
    uPxW/JggDXPi767yPhCf8SzhAmkf7knBxoftBsYm5ytx+StnNOKh3AOpyss/B/fF
    etxA6qOahcrTHG2KTNAUlTu5hcP/of2fv20QUB3uCxU1ieoNRGjTXoaachAGgIHS
    J07667ab9K/lAgO3u9oLyIzZcp6Ih4x6ni6oZ+EUSe2L2n2FCO1YfuN7ErwxPqpg
    7UMu4zcMJERAUeaRfOMgubGznYkOJQ2eIpDoh6bK6riGGJe5Kx/WenGiORJaaPkD
    Xws8eR3vJqJf1fUYIAC7O+WwwoZgEHxxKWI1g7RTz1dzJ2m1sLSFyZy5wJqjQLgL
    nSGMbkrrvrgjc5FX8DQpiJGx2MN1bv+5D8n3pXhZjCKGgsPNLPFwIeSrQUvH7HO/
    CqRBhn6DNjVELBA492JQd3zH20FB2rrPoOjMukArrWV0SxOVwDV0rbZKHVoOh+eH
    Vn9/FxzH/OogzpNl6OwSN+uB/bLbUo/ps7fUOjnoIVdHewfWPB4xUFRT3b0eXFDO
    FZ9QolpbUWTgNHDImFGVHlCvFBmFcY//ylS6KadYe62weLbae/5ZI3Y4ozw5Qss7
    S7NIHi69OoKdlB/6Ux74elE16wxlTQCspwbIW0+KknwbE+ub6JkB/uMxjGq3bFtg
    WUjJg9h+ugtOeZz46sOD1+ikENCmZJMX5FMcpZZADimb9GNHdNIDtHcqWL0oKgZD
    7dFvCLmKFDZIFMFu3ke0wyejYb2Lse/QKsobtw8iLEykWpx7zcYpMufljb0c1xeG
    N4HpHxOL79cB7AiZxlz/VeBE9yquf34MRm/yNceh0iXn0AMvcGNmfSZ8b9dNk0ac
    b+ocw4EtRlS3ao/lqcrRSPGRDZXgI7bznjLmuQiPlSXx3A7vKq/kzU/WseCD+GhW
    HibHDYwJF/YTBcY3Ug187wiTA7T/Xx1Kd7eZtRlFAnzass5crntrYx/ozHSHxj6j
    stoohPdMgDBX6B0n/gr2K488FEZybsUrfjih4gDsK5zTOlDE0Y1pJ7fVDgjtWc7O
    MM/+coYeqHmJkGta2l8KYMsRXj9NnmS3pmzUB09sSWiHg1JeGSYBO9SL93ZChnmy
    DYA381bNQSiaJdim85aOzb1/6j7TJE9krp7qKUTx0sB23NBZZ7HevkFY2sXAI73E
    hxq/d9jOIvUARIK5SrMatnCcCS+hMpbHlM/2f3NsqHvkAt9M1wsBvVHaVDoLu2bK
    EzXUMcUFQrw07aR7eflvkBxH3FgJPoK8kVtLqqzcSjPGMMzTE3YKN+tO4NP7Uj8e
    SgYFNb+eTmjC+u2RV0nw51SOFzhBicCSQG6pI9SAm360Am2hBAGTRRO7NSQF2Eyn
    hNq2qIMC0seJ0NJ/7lON3mRYA55kyWOCoygqykbB7qE7tAU2qY0HQkCdMvS8yB6G
    LrE7X3Ai4lMUsglolnQIQ+PS7eyhP7DeQjhfX282pURANQaonQzyPz7iHfdsuCEd
    kZPlEpLdjR8Ejh+WTOzX5tHcxXdRaTfgSK27qceWqbgyGBin262m/DUYOMGn2Lsd
    4t+/Syrnu2xYNkrG+1owrrfAWA6FOUeN9OuQOheibJlFZiw1xElLmrU7hKZpk5i3
    CHxao6dxjSYG6d2AWM3QVcXddzdErFzwKshStzavKBEsn50/hu63u+DnnnScecHU
    m9mgn8Zfa98PoqZMwUriYHv9Mm3umFkN9Is6GYY5r7P5lgSoIZjUNYTXigby+WOe
    LNeszf2Eebt6Vjv+NOvAcCba0TEbPj90o6IFP7Eym5+S4oSG7Cu12qNMxBAXFIOZ
    2T+UrJjK5fG6ZbLCtuRZG8b214TIWsg7+z+h7mmq/TVvtGFZw/xQsdjJBtO8BzRm
    i9Ni4cwWYbu2IDBwm3Dju9p3+QmSmfG6yDP6Tj1kZ9kyUQYNzU+cUmWcidGz0QuH
    VeHs37mLQORG8RrcxtvAYzg5yMq76IC5bzyOLOecl114yONBCvudiSqZ2p4AOC0u
    fq8EHX5/CkGDCrvp5mGtwLZFxpGBUZf14PdRTiFVFk/rbIePsaYjcS0Zm7iaZb6N
    uN6AHvV5KgVfStG7A5bYPkLZsD71GL5bwf3P5YALiSNPV2ltZzSTzhO5GRiQjf0D
    IkgwIM0UfgUhq1njjhZUT3bm7IS1xNCLbbLKbd42XNb6jOmF97JearswW6joZzt5
    T8BHxNuOreWahqrb3oE7D+E+JwuVQheBV73WmN7i4ec+7lRfXtYuHnF3x8jBG9Xp
    8/OVnsaVzW4FqRIrLSiiqY03sB8J9LjFuLQrJNt8EmI2ivL9ZnBuDSfUvrt3ThZy
    le6GzQ3IbAzejkCdxFguVwtBgAP64gD/6QVC2LnljhXjSqsXoVOJK+afBWjM5Dfv
    0VyTf5xgeT1z83vxLjbNSHt9kF5V9vYkrEns9iqwgE//jL7te4LZAeU35/pi/Wp+
    w3nvGbP70AtRPmOhoErH9wer
    -----END PRIVATE KEY-----
    """;

    // Prototype ML-DSA certificate PEM
    public static final String TEST_MLDSA_CERT_PEM = """
    -----BEGIN CERTIFICATE-----
    MIIV+zCCCPigAwIBAgIGAZ2xSDFuMAsGCWCGSAFlAwQDEjA/MQswCQYDVQQGEwJF
    RTEXMBUGA1UECgwOQ3liZXJuZXRpY2EgQVMxFzAVBgNVBAMMDk1MLURTQSBUZXN0
    IENBMB4XDTI2MDQyMDE4MjMxMVoXDTI3MDQyMTE4MjMxMVowYzEaMBgGA1UEBRMR
    UE5PRUUtMzAzMDMwMzk5MTQxEzARBgNVBCoMClRFU1ROVU1CRVIxCzAJBgNVBAQM
    Ak9LMRYwFAYDVQQDDA1URVNUTlVNQkVSIE9LMQswCQYDVQQGEwJFRTCCB7IwCwYJ
    YIZIAWUDBAMSA4IHoQAVVz/MKdyrMKxdAjd1OuwD89Jy7tFdcfZdbyc8gk4sqRsS
    VYNU+c0BN3TMZo5NFaUWRKto1a5Zem5pD1RBwmJQIoK2LwLKP2cu++PDDcXIWoIt
    d0/4vq/pZYVfdvQ2No1K3/kZnsGHS8b9fckucxIbcHtCnTdAO+6RCUc+nRo0maiI
    2zqdnPYiXbg6YbS0Yc4Qc2Tz4wvP5W+uLg5mxbQRWZPNOmAQB/1ECu5hTlkyhV5H
    rimYGcbU6wkBcFQqaWz+Cr8vEfcOiDGH1tjjGjGSXPV1OMzTNpYu22/CGe1Jzrg9
    l/2dDZJ4PSs+knZ9c9vPerpTBOQp32HTEv4NgMumaPYP+BNqjE00vMX1pbzdWhnF
    P+K+9zc0IYL7BYQG3pAoXYGf7S3XHAxEedfmSdAmTw4zEtChvToMj0QbLC2EN0NL
    CgY5zfp70ATzB9JEk2MtWqQhdc4z8KY1zbc6hIMJGdrraIBM6+sipewSh20Klfmo
    noVoojZQqaURNkrqltKSTImc3tiNTrQhuQE+SAO8DjHzF5q+qURUW0qkOlJFvl2x
    MR/TZc2XljeSn6K/WkfAuSAymJtnOE7muZsrBmcYnluRpsJVDFQVRZZZbsUU9ovu
    QNa75zcv7nRxUDjd0NXFHotrif3cPW6235FsaU1uumqKEIB2o7eSYbIzVnhwaaBJ
    DXJFmEk0Th2moDUaoaCLNMvzUHvLNpxF9EDtPyVXtXb9FmCpvs+6MmA/jprCYHaV
    Ht4N8vcUy33CJ1dkNXBojW27SR1arO7G0XtsMidLRLZ8DoonjSVEn4+wI2qY2MfS
    VOZxa0t6+tXOFTdThEh39aqkJ9qrhPmipHumqKyRVHRebhtCkFLr9HyF+tzOtMh8
    f9OSFnwZwZ52Y3ZidYkz178n+6+4dXrGBFDTA811sQVQm08BE9Om2Mx28PvaDChu
    fyj07zNTKBTaRMwlbUy7+qJtJB97J8QK5o7y7I/2mYHTKF8wC7Jwd9y8QPu+lLLI
    x/khleWSE//BUX8Gxnj+VPfwb5i2RUHJ+LzOl07He9hNIyC3PVizsknqpBUzrsrS
    e1WN+FHLeFD6UFkM541GT1r+TxJUiy4ML0MbLFPLwcxzShngjcCrt/uC/PQk4pDN
    ZODdst4M7a9yGK/9AM8JE2g1+FUCmMuwb6GkFeqIDFiWLK5vXmW5kMAeCM83OYno
    8l4pFV/FKitNqK2/FhzEff0acJJGJW3PoarG++ueVSiYZum3U5gL4xkc7tKvpFUt
    6stnaNxxbnwV1oepCuwzIxT5TztDWPzTNTBEdf/77w+VbLLv44LRYozYAe/9V3sH
    U3XddR81asM2j1nqFuarmvxdM9qERPsZ0Gg67vh+dfp+CIA3ryVPg0Hj9i0zWS2o
    RjuoUfuC3puu+zOCJkkD+uX2xQPZWdlG+pOF6GSdRiQxyXk4jW9mY5Nj7XnZvAsa
    ooyniKQ8blo2zgYxUb3ZZumS7Cce4qVNs8QnZkx9ge/yrMuX4dQBNULvCQiQmwyw
    yTitSOnVaAdQVmWa5cQKnpRYYzdbFb2hZFAWh1I6VDE717g5AV+rQCnhgzv6QR6e
    ncelGl0JmAxCUHteaAVdCoAo0iVK33DYb0C7yBOtxHmnXbvfeFZ9SC7LPB/QcOwu
    IjwGx6vefE9uUO9wtmY454I60lzBo2fW3vcSrW50lNIdt70tWfmE/7qggB7ry+4s
    KH+COT1i+YKwvzDLAzZFHT4z3NqLtY+6vDhukJC93ID3eh+HInEohKiPqAClqYXw
    GhkMN5k9idByKcYc5/izyzOm95GV7Scx9rBfLhPB14TU6Mw91Rz/VwEBSHANGLvX
    UaJjaQ2AJG/IiFZRAtzyE1hK0mhgNXTOHI2ikb1eRCkbUQgmPMIOGKbRu5OoAcIc
    2fyw6f2sO+julEBeuKSc/oQq4eowZ6PWwsO+Hn+BXqnOqTJe3oQvhI6Jv7xvRlEq
    2a+/9pplfe0+4T4XlBd5jBqkrL//ZrhOk3uvIKAoFZYU+DQuII3RAuJO6RwZgpGC
    36KhztqT6KbZJN62nWpbTLwQzp64rW7cZCcSCL1IohAzKoC/ZrJaH06DcSB0QxLR
    at+vkBYqXZ1em2fjUZ4JZNYQSLNekkzbFHNJORzNhBqZYmCwJIqrHDX7F3hMp9vB
    DoRhWibGRrTeg0VOaZAhShBkIdwgbLtF0dxACL2blOaocnhQdbM9MNlS6Vb3JZV+
    xFuT7O9k2MHnf54RFzSF+ND1UgB0v+XIThimWSNXM9XGB6a6aCuJy97G5gXfhCBP
    jh8/omj2ZokFJK7h/mnuwY07Wy4q1LOqWZOuVAhwwbcohUpt9M7g6SzkgtoQxVVx
    r944xLOj/d/sJ0Ier6EARLHOvC0YzMaV+RseP2s7EQiraNAGNZobjCKdIKUzuXkl
    N5nTRQeSm/dqYhxJKmx8U1bW/T28uOInXqqYlFPuyP9yfzrhTztfdEa7ZY/2jIAm
    6w5YaqyOX434LvmaWAC7XavHxyBhPiAda/JNv0Uzx4igm4DYHU5/t6aoiiEpS+NS
    BVkbEVlr+ztazBR4OpTnvtEmV9Y7X5immP8n3EH8bVEvaJT1444yeyHviDqgu6Ng
    MF4wDAYDVR0TAQH/BAIwADAOBgNVHQ8BAf8EBAMCB4AwHQYDVR0OBBYEFGhCdiYW
    VuRldcYd/9nYNf2TYpAIMB8GA1UdIwQYMBaAFCo4bw2sIHjMLMUQS/9ZXS9IPhho
    MAsGCWCGSAFlAwQDEgOCDO4AAAMFSAc13evw8SO5o5JwwFXGEk0tLh/nR5vvtA9l
    cjOuDNEJtJL+Na2yQUOqQ9Dqu1ALhHJH0CGipfGT0jWIZrUvdPJTapXN7CRH/1s7
    I2+Hr92UScIO1UWr6MHlSN853yBv0XNl2golqAbFf0tCRHFGbVaYeSpCCCAdf1hU
    BAO7AQu15K3FvIUC9nr/eH8gLkyI7iM3LJIXBYIGMSLG5AS9xj0Pwsh52GDnxaq0
    5wwDFGUu4TEJZZXrCRhWdgOQdn4KshwryZcRqSOUh3KZ/WJZsFp2FYrwAkEP9IWN
    1127+f8L0PPzHiSGTaIpn0AJnN9bMHhSEytAlB6ro+cJU3bYGCsYX5NulpzHDkJ4
    dp0opHjCcYmaAbMcpXlbPQYUnVb9BzqdpQPgD5SqjV281zZUSXbuWaqOzNi4ONnj
    ninhDnhUjRwFswpmDAhsp8nxspz44FYwZgkluLSNVxwRoq+ldHzQIPYHtSJn54jj
    OmNz4i9YLG9MkLsgSq/jbXNlpVijyy94trbKOMRVMEXwpH6yVsanVyh2qvCIkQul
    n5S2+myAc7I8/4Zin0WMkJWXSiIQyM2p4ow6ys5rGqDG9PjMjcLlr0GlWJ3VY2FU
    xcgF4YmwNMNeFLcSEgGEqnj8QzykxuIWKAxOvYiRvRh3bV83bWlPQpfRT/iLFfTk
    LHGUlWzn+QMRd4OnvD0I6QhSYueFLyd2fRLsQCKViyEOfY2ojF6BasDNv/yswuIg
    4DrXQdG6hGhevDKFIEuzo8c/MGcgMs2v30REOyYmo4aUehJCuKTlxKrNwpse99WF
    V++Dpl6jB3d13Sd044F3/YWay/do3y3oIniMAP/E6CuinSaP9bcpQnhlDxVv3nQx
    9dMK+eRlC2+KOhRPeQSmiKZNQlujqMlwXxTlV4kLQxAstBBVlKXbdvXolfgYUKp6
    LNICc71uPrcGCtINCUf92+XUPhQwLnm00G84Yi45rN0kIoK+S+V+QF/hsbPxq4q/
    Yl/GWC6qHgg2/mNU0itmI7yWpLrnzoAyPfXeN4M8w48Xu+1dh48XYo+Rp2PWN5Gk
    XJvmA6LVUbZV/2t5mVZdiwQp+0oYvPOul16L/eI03kQ7htPeTRgB9f1vtViAxgj3
    nHUuq+Txwdyidevixb5ZlN0gpcf47I8nMmUTE3/ziVxV9uNdqU7vnotJYC9EPjOU
    XnXfbS5IbCKHzxuZSyzcWrvJuDJ0iHps13zJ4S7N1QWmwIfryN/4Mqyal3QWrBCx
    Q/DP1BRaENk7mk/dQexH6wR+6EQJir1qyXyFpZK6K1seCDkimcbNL9RhfS3tMGw3
    F1kTlTwJUZiIJTTe1dIf1Us4YIC5dJLpkBVbIMc+AFx0H0/hrH2VCzISKmGGsbj4
    3awORRuNDayMR2YjYjgZ/ikHqMitExeaQGHdxyEUAtPwpMPzRdgdSzL6ct6xdC23
    x0CdNwtDiiRKRQsVGkyIndsk+bvvyWReHhLDyEoNqHc1qpF0P+//I89GMyUSfla4
    bcWHcBs0ZhLiS30lFEU+Ba3ms3zGjMbbzK+sTrISiWM4UDr/55KeqUE7YU0wvFZa
    dqvNKYwFwWknIG+oquVtQhZgKulrVutMbwx8FnijahyMVxG5pLen8zV7q9AFmQ8l
    b5ZQsEvyVJNUddZZM0ld48TUVZc+Tn+rB7yfwgCxWoT9gSLxSnsNKAHflo3r7/Vq
    AJmQkARF45Mgq1BEdxVzKBSUG8fE1D/Md7QPtJSpeqGtIozQDkFbF8bMGEoif4bH
    o00Z6mElnajEQnqT3UQSJIMAHpxoONH+EMdxmxssbI8Szr4lUXWJOqPsQRUSHeI9
    s1b360o745Gi0rJ0Ri1zGGKqF1aVULeBtkMmA6yny5/9zIXxml+vfe35rEN7nA7o
    yt0uXgWkYVz4BeWWfGfBfQhnSLXkLJwv1m+lnAXDmraMIeoUWTkuyqc8cj86ldgo
    ZoMZNP6n/nKjZ0+P0/yC07bJ2KjnOoIxIeXFs4vZCh27iFKSWyqUFQarag9Jo1la
    6IQKbU4VE7SmpuVDWChigP0P2YMhrjXXVskC57R9cPumYaVp5xoo/Y+5Gvxsz1iW
    fkfKG4Z3WCk9cbWq5URl3VlswS7o8MmCxJ/1e5dO0aXh89EIsxOZy9ZyofzLh6P7
    W5MlDAyQP9oNoy8ghYS0qD1BnH8OKy1YIVi69H0WUQXZ+5mmYOAAQ9xTpCj7f651
    gsqiRCdenPi8PJAoS0WAsMgjCPglHGw/kcr5fw1/OIQPKFrQlMZx2I0h578WB+v+
    4FHsWBmMCTYHZe28fy1l2LuBexCgeGyxp2J1HaHpigzx3B50sn5Cj3803qaOe7mv
    DdxHTIq/fb2uZdqkFy72qtr5IyFNyp4x/DI9CCy7BIiBeBLj+dAopcvaezlqseXc
    41QLoiKihbD0pBPuF/vCOfF+6FPYJE1VPi0Ji2scXmI2nYfH6oHrTLlM1qwqn8EN
    ECiR0gtal1mPYm25RgEHXftfrm5m6BEqllLGD5Dmb7jzOJ/9Oz+fGEgYOPb4mDA2
    EqGiEXRiWQNqQTJxSPQRFFPbX1citSuF0kfFftrw0JFi/g5F6ilPlvti9LNjiGyO
    HZNLtuxMPzvU74Hiu0nYkSWStNrnpCLnxeeks92gE6vYo7uaD/CguDVL8BJmhQIo
    dIHJsRIj4kuFthxDr5YR69PjU/KY2AAFNcRL97ZHNZNkXY0vtHzimXYdhPKKTYeK
    tDRDaZA7BW++VBmeqQDZpOdXL68j+smiIDYlaN8oG15C+qtYgoH9eAseGkcGH29S
    lsmn0jFKCTvytrDW59mTBTbEW8qT/a5LBjrrFH4kmrcLMo3GtWbWnriSO5s47Opv
    i/J2C+V2wHEYKsuf01dKJHA7DEi02M+D7L0YxxNdYPd7aMtqs7B7xZZzs+R5uTlk
    uAAXWQ0YDj99dP9R9lycxbF6Cehb9M7VVjR5wYduL/Jcq8c6WzzJZpsi+IMtP2vi
    9BSFsxsjPeSXRWmHz5dFaVxy/Zw32qMHubdDa4ol8GTDx3HYsjrZR5f6Wc2iwvX8
    kA0jebOPkv2NEUWw9tMbwMhiCTCb+5KoNyDVj8IO0knqMj6eItVQQBhdlEng3KaR
    hHTLFwFhQqoD69XYBoCk3F1/YfiMWxyOPWaK6e5k0f8MPs+yRIozeZ3ZP3YLC+OD
    20kgoKb0APj40PXn055Beis6Sxn4whTEfHGh7+1qqIeJFZ+lXl++fIpRozYNeBPe
    kOxtGTQXYy6xhhNF4nUXLuN+ZTAVAIidMRyP0ElnJ6nGrZ3tfKhgIL8Uru5ny86S
    zYEOcMzOdhh7H4Jc3YExZtZA3GoXPRBaG7xrUn/Ru4fphNpE1UvRjTvm9savDcP4
    srXOooda2NL8gdtaqy5YbOxQpZ1Uw2i6ONDrsoY9Pl3o+3kwhU78A6MNwLX2OxBg
    mXR6v2xblF98twrvq7hOj66l/XLlt8faRpCW/apn5LnPRiXvR1SKGivtXMbmKRLa
    nc0/HPewXo1w4FmZLytP90FHpfgJLmriCleM8wfB6JfzGKMe4aT5nZ1d3wt+Zwjt
    lfo1xtO9fytklGVY0NzMoggyCgHGVYYKJDXnUhczMqPVdWxfOJ1Hq7K9bHz0rycS
    dGQ+UUkdDpfWvgJSZpEnw0hisJLVGR0l9eOa5tgkaxC6mVHXGZUFuRsQAfhH2JTE
    EPItbvsKg0Q4+4unc0Lk4ssL0PjnbcHSxd9nObRLFM9T0hkA6r8cByDu3jj8XYCR
    6b9m347JKZGkf9CFyS+x+bBbapBDoXqFM21V3JTzlP51dNCWi+w/sPqUg1ngvqHi
    58YAcNqJQA/0RzpQILpAiSWCUnWMB3+Jy68mhdwb8XO5hmPvNgB/Lnqy8IGiiYM4
    b1qmfA5bnP7NhVE/rnL7yAdZ3gy6t2nUHy1v5xbshBB5HQv8lc2NLtkT0aVB6Pem
    ZhCLDHNUsqcxy1Gj7e5bj93fuDlVi4UK94uJ1XJhA/iodF+Niwi4Lt3bocU7nEdk
    YA+onbgo2XbFUyJUnf/rF8h0tmuMWyFHAr7ZkIiprQwMIIJk2YXdOiEL8ecavfLh
    sv4ijy/w7hQaFCKBCPFI/UPPPxuTM4r+kFoQi36CEFf7HByw1LHc+hOPtS14RqsS
    bhmQ/7ZgVKikRf2/ZdyDkCQBRU0gaRLuiLpW1H0Bw3H+piKChDlWBBpGbdhdBmxn
    htQKwrKmpX1e4XUagnx9ktRi1IAqnK0T+LQvurHRhNXGXLKSqgEXDV37J1Pv3hw8
    d96WR8hOZHj9kyOWTIEpL1cCLdzenxVtW1fPcjgVy4eZFAo/08O5FtOXTPVSjQQ1
    6fQHJcntER1ZcI6ts9jxAFtsdJGTCx8zYWeSys/tKj5HcYCBhpGuxuQCBg4jLUBX
    XHOFtMbfAAAABA0THCc0
    -----END CERTIFICATE-----
    """;

    // Prototype ML-DSA issuer certificate PEM
    public static final String TEST_MLDSA_CERT_ISSUER_PEM = """
    -----BEGIN CERTIFICATE-----
    MIIV2jCCCNegAwIBAgIGAZ2xSDEEMAsGCWCGSAFlAwQDEjA/MQswCQYDVQQGEwJF
    RTEXMBUGA1UECgwOQ3liZXJuZXRpY2EgQVMxFzAVBgNVBAMMDk1MLURTQSBUZXN0
    IENBMB4XDTI2MDQyMDE4MjMxMVoXDTM2MDQxODE4MjMxMVowPzELMAkGA1UEBhMC
    RUUxFzAVBgNVBAoMDkN5YmVybmV0aWNhIEFTMRcwFQYDVQQDDA5NTC1EU0EgVGVz
    dCBDQTCCB7IwCwYJYIZIAWUDBAMSA4IHoQCiwV6UxvpVppaugJo8Y0XBg3fdhnMR
    6lmVz3VBCqWNg5+42A2wCRNDXSNoXdE65ntr3jXe2Em9+5oVpn1Qf4kA2v+hU2ET
    mU2ohO5H73O35R7g92WO9bhcptKuaGW5tG8bPS5gNqnWblbg+5TZNLLd29h2Rbqs
    CoX6fH9We3bttNgLtebF26UqP4OPhwpOIkGjsgXhqM3UCvEo4REQ3CQdokha9Po7
    i5UDWuQ/Fy9eWKMv1BL5sWwcWQRrqWK3DAOjQpVZpFbJev6osRKIhLivUxI6ror5
    dtDvPJ+r7uGaSAA8fDZw24362L1MekvKFZq+Svcjhhpvq+hhoUnlmFbHS8oE1Dj4
    49cKlgySUwgcnyL7wb2yfgHj7duX8P1hqYVVlE2ccPIjghFZljGah2ttpVMY6Mas
    8HsbYuudTuTlzVQPnCQXtH9OnnhbUVLmT5zzlckey+ufxoRvnmEU5Kou2kT0axWc
    w8BcBCHHP5v9T+InxsfB5oiNcsY14kfu6+UT2u4I4lqG+RRnUVp0Lqv0DHLdLL/s
    VQn1HnEYb5ndEUMiG8opB/T+YzV9dTjwdrOejiz+AxDt8fuTuHM0qX9EheL2MqUr
    2XrV0kPoMQTr9SIxFWrDYNWZbSva1uQt2yGqGwHdWmmhpj2udHmyFqEQevqHSzdX
    rtfP+yxYF/e85POidbnsIDcyLV7ErFuWNw17ajXfLcXxzTolbZyGyojDHYG60mN8
    WhARjTu+/EZkGZoYg2aWf4mkqBf8wiYzKJZGTq8RxQjcDeGI+2AVxvtAXdcPEBkW
    iLEBPju3SlpxqyclAugnSFVdTMTm20s0ZZmcYRkXkjD/XHtpUNoxuYmMoYcPCkGW
    i5EW2ZBHA+6qsktjo4n+co05Q1WV2zAyCWPWL5gfmUJ5+mvC8gJVfH8oyQELnRSc
    gWDt3Swb8FtYDh0udxs9uGt4yF7NHPBVKxdIyBKLEzb2sMKKKzjPda7N3bCZeN6K
    OMXz7d+MWwSMlDKqOX07+fBFzZSgQ3VTbPJDUpiHtYrmgRi+dQ+hfQ6oCwvgj+0y
    Nk1S+9d/NeSh6FQSh9V6lnng7oaATTkOmQe/ccewsZKto2AMesp56dDwDZR7tZ5B
    ZpurjYSrEitLZyOz3EwyOWI+NXHv2lMWHaVZ2yWg/gwUyO+Nn1SJD0lKSI3w7tXi
    zOT2A6FrimzwfR9U6sPNhTXVH4n88Hnfucheh9itP9YTe45JcKRVme6kQYoLlM0R
    2SC75INiq2DGddieK1RX9EKl7or8c6cUPTEX56CW1wZv8IP8lqkwvBplwZlnRRlR
    qt4OQsUdkjLe0hTKr7XpEaauU7OCHmNuSB21FjMIqD3rhF+COecz857axTEiZOg8
    nN1vv5FEIQpD4CUfFVsgpi7JD8HFo+tcu4zk+NDbddAK3iXQXN1vEWCbcXjkSKXn
    TGcRDODKc9JiUGoZfF08e8ZFNcRXd8lR8CaNEEBZtlkut58KHanp4V14eut9jH5n
    LBRWUbXrr1I76MNLBefHxBcy0CI0KVDCJflv2EKTv/vPGAyz034uoV9xumtYh8YP
    N0xMl8dNmsMNutZ47xULKKJt03QwccXVY2ZNbNXZgIbntRGdk/kWotp1s8Fc4Fuc
    uL3tfCiQFQAo0mfxAoVBWk+YRm/iUcqJIM2/vGGFaDW4Eqrt4a5EzGdbiLqeAu9P
    k+o20K8YCw7paJPi9ZAeOKNijZohSvL35QmCliz0f9dPj9wUyWYkamV2ezUd3LAF
    c24vEbR2GXH2V5cPWDN2nDNKr6saHewzkw80dnhF9XCiST2tkjTCgIozRe0Ir47R
    s185PslDUVUE6TTXgtZ1diVLlaKWQJVheSgGA3/siONa8jtAzP5gDZ1DH6UCo775
    XhnpOVwyINSQBaGYI2pauVhH8mJoE1ZrLmAxQw4PKCIybhOICz6LQODCJCqauYFo
    AmZ6CT3GR1lYek2xx5y2uOws4GlUNHpmFKWPx7TeX+9u7UfhGgV+0obVXCIk5QSD
    njA4nR7beq1cGkzv26zKZI26SALc3oN1EHvbjw9zf4jZIhTjt2WFRz2b+eXGcP5B
    yzL6ddB5q725dmU5AHQDJc4IIJXoubAISoEjrzv2GHv+gFqPmMXscbdkli5QZvBx
    21LxKO9IJFj8mdPS8b9h6bes/kj7fRZ+9rjVVBmb3rd7LJJecznNsZ6BGULZtrZc
    AzfwsqY0KIHBRVgRrV96Bq28ksYv38OQJ8Ko0zcAVhPJKv84Jn6GFa+mjEVsTPVx
    F9kUo2hrt9VLC5I3+V5jTjJxKbzePqoW0SqYAsi6ex4iOXjqrbFaOLpNmkjDhi8L
    Uf+Mi2S+udhM/lOT/97E2PutKhlwNXjAH0NL7yWRMXhChmfSXf1VCQW13aPUyUKW
    0Dw+N0zRIrcVAVeZYfdsU+btdww08x2L9jV57IZF4C/QbtlLJ73h5pcsjA/RrvF0
    3Dr2LoLofMu8dGz4EPa1Mpwin0KYjKdSPDoBru2r1QjyrOUa5fLMadGkutKCXhg4
    c82PKwhbpAQ7D3yLVvgVTE1K/1Cd2U+BfC3xzfKGIeLv+aQQnjybCLmpIvGiRdK8
    gmbdel/BPIsTiaNjMGEwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYw
    HQYDVR0OBBYEFCo4bw2sIHjMLMUQS/9ZXS9IPhhoMB8GA1UdIwQYMBaAFCo4bw2s
    IHjMLMUQS/9ZXS9IPhhoMAsGCWCGSAFlAwQDEgOCDO4ARdIcP+BDvZsNU04B3y93
    Sjqo4oZN500xfjeO7X1hrJZrgW8hA4DJiaAy1jyjsnXP37VW0UvYx4wP+CYEvaMK
    /EA+Tpmxy/O98y7WJ+teNKbh9BwIh5PLzhnkoaAQmsHwIE6YRK0MBuHWFtu8zf1W
    ax4MQhaQdxExpFb9x8IhSM9Dwfbocul1UtJLjC8jLqE0MSXtpgnxYrrzE+iN9XTi
    PKYOmb081L4UtRDNCHU72teMZg+PpsJ23XdN7DB0QEC8SWFSZnX8gDMDVBuFwuk1
    cLdLldAc0o7fYKHsC0jhCQhZEBrTWvoKZvRwP8mwP/24sbdX5ERojACU/x1+7GoV
    0wqvdePUKYaAF0GSdUbLUgIel/uPtSCUJtN1exeWG32sf5b+yZnzXKd3HYeifzum
    PBndw+/F/YsP3x/Foe1RrTh0ozrVDB12ZYniBxde6I6SEVin8XJbNXHXRNrHkKK5
    2Brly9Jd/cXPVn4HxB91jays+RzI6T89ivuNqFcUDxM+MjkmnJm7UvUw5tM5M8Yo
    +WFnvt+NOJo/LJ3cUtRUIDdnDPzDvy8SnoQ7O9VNn/FzILrmku9eC565Zct8SF1M
    aGJrBqZZ5sWHwWt8HHw50kpJGFwoYdbC22BCUgyyH4M8vTs+gDRt7E9dySkJQLaX
    tzdkImRM7N3d8xxgD5SzDDk0h1/p9/7ADvHySUxPnjqZ2QpZem+j11E4EMXvWxL1
    WCdnOSbpEJ+rw7shjbY1i7uNoeEjw7PRKb2zM5dGdIfArQS6oK8iAAHRhHJwVRZ9
    XqjTI+TvGQ+Y0UY2ZmiV7A8VRxI8DxgDJK0K0hVCFT+1qg8v0toIVHb78oVKpbIn
    dsilJMHwOVi9EirED2Zf1q7SXFcmdvU8mJMSaXFEdF5G5r3KN44MS2EjyQSuIl3c
    Dnd93C3SqbAVMcaqOBxptlYyCP5k1u0Zlcg2CeR2VYQRRxPPmJ/Tkb6Fnml172xk
    JX4Le4oq8i/pfABS/O+OmGVQAU+0jdTau/rtI0mlvP2rrgeIkG9CYH2BnrMJAPrP
    FOF5oysuKafwk7+9EU17oJE1sC3bKYzeu4Pj46ytSEkdV8II7Oef+flGLw92Y1Bx
    ny4P7WX36BB9zre4hmpcrZOE84ka6lWy32uFMplmiS3uBXfcJexzcJ1eSzsewD8e
    x+vCGJ99JlAv59CbKuISTrPNW7HFRHinojopDEEnS10FpzeKvrB1G/I5wjbJRotc
    DURDmk4kHYgnMvJJd3caC++/Q+Y+5KExAlPVbt+92qh93FaCocgFTGcAMagesKuc
    C9j5HUy3pL2xU0gHrICZsjjfmwmYRBHt3KvpVYPaMgH6+975IuxSvWkkYa5L0Vkn
    3iir+zl+nUn+b7qC0kide4wRtU+r5eGhSrn4jmXGV6QgiIurb6fdfGQpGhzhGlAY
    gF2UXS54GDUySNKlPPga6GeoxqfNXNid2lJ+HX5avQ+KCzgYaYCWYINOT7qOjPgN
    KN9Axuw+c1ZL2ZBW6fVRARXdo08PiTHOlG5lqy93aCzcuQ+mFzN6pJ3cI4y3rItd
    Ih6Qn6xUPGNpYSzHRGu9c9f5VtJHM+FjMcGSnXDhzqFf4swld4mdYBh8PvOGV/ME
    SI3wvJiGIddXq1teaaI1ITP+7VZ5x35WFZPC+tCikib+QA3J2nvlL8Dh6BqyEIV6
    87CjDwSRqEeZQPmLRmKkDFwu4qwrIimiVoikdBSwcOUHW8ww2FycrInTG/qxC+XE
    y++YL9OHq9PoD8XL60PThtMIY50DH13fzUWMtAyPKlZgF/S+CP+kHpUOHvZRI+N2
    o0a1V93Zam1LzB9/eK1vKE/xLIJllVAmlSbPbOBtbOcgE4s9KPlv5eje+i2FDuJP
    lvVr8Mb5x4lu3u2sYuhLo6PpRQxa3CReNehkgT+jr/JMR29iqxd4JQ8loMJYcz6y
    jFtOUE2htM8SXRL/ccGAbAPoBHYlRipgwvagMxtASzWJPCUkW7+SXOIS0kVsm68e
    MmvUV6BAXpz8Bb8p2/qTGFBF/mE+IVDQv1tWNuP1NihU7XAffjIXMsSQlMxKRSGk
    bmuzd6vEiKQlasVMHvZaNxIn403TC3j7XusfNDZ4Zfoiyqe4PAhRJf/ngATJOpxT
    2oqXOuRFL6sU5howvNTz9BftTiZbaZEKfFA6VkOvVjDL+eOF3L7en66CeYItvZOt
    3s7G9D9Bo3ua8JfUlSA9l6MbKa/43kghPywEssyvy/1HmfT06WcpNYpdlJRjmgAN
    jyc82jCOkx9PdgzrwiVK/Vl4u4h9tAv6UdWoaSMhL2Dj3XjUbqfAqJyTUjG6nL6R
    wZEbdJwhC6BTmccA34BrKZR68ASWNEycR1IkT7yEW8ueH7tRyAfTs1uNpSRp2SI7
    GYjvpDtlDIfg/+325dVAinI9nkDlbMZ4Zj0Sk2vbyUxnN/6e66FnHTilfQRZP1H2
    SgrFBPTQEHtDcob5F1+oUL5Z7a7PgJq8MFyaZ9gl1ZHoazp7vRhHVVUwLxeUKL5Q
    GUTW4OER95Yy1+0eFHn4frfY4JcBT3Vu+E26xY3HGU0dB9tFK2h55HRHydJEStxg
    AQmRyg3oQH0ifCufTG2uHthyGfYPj13uFbnErZc2QElxNOgyCHz/ytLC9c9SnLej
    KvqgD45PkAxR1v7b8zh0ixeNt9gfHKdSS9idjgjR/8RE231vzfrgagprRUAup3wJ
    B7uG3Ou6qlLQLAgsvn9HgptXyUTadPwGyt7hy8841dXKafV7z/u9xrCdOV1LxfE5
    1iJ1REMEXpASiWknVT428T4S44/R1dbB/198m/iczj6KA+FZIn8SRs1grWGnTMA2
    47lkUjWRjoKFQGlny+djn49phBbTn+58O/SvbxWEQcYSD2Em+kMn+JBTOF2zoZoa
    cqHXv7DUWk/TN4nEtjV0VFELRM1/iHgim7TDfTp3t5SP/89roS0wBmPx7KLUlwus
    r7HsiKV3xIHB0PwJjuHJqYKlAKRkR6k45s4vvifU5ALSBS5iVE5bcojXQHjmYdXi
    1AQSgRkdV5Wp/ABny4h49xQ0Tg6lYZRVRTvdVsDE1m2Sy9xma+E4EAGK+m5gBZ9P
    NhFTUJhuF1KHcjJVpjC8cnG1wxifef3iy+GspaY3MKFTmH/BHcXOpjMaf58CNRln
    Ykp6hPKS62z/sNCeJfHNKev4mqUSe/nV+XdyzwFDHD0X8iG7T6Z9i1KXfGAJPTu7
    vAy18yYyqP//w2GQxcngeUfT2WS1Pbyzd/d6pXHaDGhMAbIw3B/xCAhzop2y6qXk
    yQbswhMTue4NS59AdIb7mAv95hac2aXLI/Y03SVPMeO2IQTeJS9WS+gLLWaC6u09
    qlU/qjmQrTrqqLMjVYvuqc0WBkB6+cKJT5+ZCIIcEqjPfLxzU9hXYxOjaeBoIS2i
    LV5jDV9FueCvGBKbQ1nMhF3P2CNZ7X1EbvHttr5v0IF1HygNUZDXXL2NWHLh4OUp
    HkVoDMrJoVMbDs9YNBnEUAZr2nERPLAcTBmpTzvSYkAFCXu26HaxRSJ34sQ8ZY9y
    tN9TskfgpZVu2FUo7g5cMaN/6CSSfjJwMmzrtCPBRVFXu14WW4Nfdg4/AcSJCGYy
    HELYWxJyiOeMN0tIAeNloHGkb4k58VpVgyHsuwkXlDwcHympR1yX+7IVS+Xn+YBa
    pzE9asQ0ujcdbbRAs5AeKcaFUaRoePaDRFFkZpq3U+yB+M6K7kX3BAToU7BiUMA9
    Wx7yRiZYGjWaR7hjR7qmrP+97DFYuYsG/hlh5kFwwTpArt0giZJUUKzdwcm8Lrzb
    SIIS3kOUHZR9jTbzb/abRdfFGTDvOPdyziFhJFwVrFWN6Qw23z1jzNSxTd8fRvui
    /VxhLzIXigccZ3mJD/qWcInNEH8l6wrxA3YJ2Tgls4N5qUMUI5WMO56GsEcGwb2h
    7QYsFVrgGoAMe2m4rfDlwU5Gp4O/+miXZ1HW5L5+nmlDL6+kcxci5KLvm5vLhjxS
    aYvteHllh3UZAfLNNXe2O1UmG3cYMhnDou7o9np/0TBCtRBZLY+Pa1NUMiHYPvtO
    GBGen/t8SRcrIvY2R8WwouTIHsZ5cySYAXN/d1iMn7wF1zgnR+ViOB/QbZcV7zwq
    q8w9P3TXahnsABNbvnbFZKRBJ7WfoNErKdJoVDQ+pQ5Czns2wLM0r1BbjYs6zJHG
    L4GeLFnvfhYI5Fxe8QqlMFW4JpsLzqV+S2ysoTHHuip6yiCLj9C4uENqzU8vlLSX
    7Keh4K1qd3avzvSPgtKDiuEzFXmpKSMMPbbRLDJNGqbLdAsAJPARNF9WQyKMiHce
    qCNbB6lJDtzlTPvvugWwp8OGi4ywGztYam3Iyuz19wUQJ1Bab4+ZouQWICQtUFlw
    esnN/CJHZGasxcfl+wAAAAAAAAAAAAAABA4YIyws
    -----END CERTIFICATE-----
    """;

    //identifier from above TEST_RSA_CERT and TEST_ECDSA_CERT
    public static final String TEST_IDENTIFIER = "30303039914";
    public static final EtsiIdentifier TEST_ETSI_RECIPIENT
        = new EtsiIdentifier("etsi/PNOEE-" + TEST_IDENTIFIER);

    public static final JWSAlgorithm.Family SID_PUBLIC_KEY_ALGORITHM = JWSAlgorithm.Family.RSA;
    public static final JWSAlgorithm.Family MID_PUBLIC_KEY_ALGORITHM = JWSAlgorithm.Family.EC;
    public static final JWSAlgorithm TEST_MLDSA_ALGORITHM = new JWSAlgorithm("MLDSA");

    private static final Logger log = LoggerFactory.getLogger(TestData.class);

    private TestData() {
        // utility class
    }

    public static KeyStore createTestIssuerTrustStore(List<String> pemCertificates)
        throws KeyStoreException, CertificateException, IOException, NoSuchAlgorithmException {

        KeyStore trustStore = KeyStore.getInstance(KeyStore.getDefaultType());
        trustStore.load(null, null);

        for (String certIssuerPem : pemCertificates) {
            InputStream is = new ByteArrayInputStream(certIssuerPem.getBytes(StandardCharsets.UTF_8));
            CertificateFactory cf = CertificateFactory.getInstance("X.509");
            X509Certificate cert = (X509Certificate) cf.generateCertificate(is);

            trustStore.setCertificateEntry(cert.getSubjectX500Principal().getName(), cert);
        }
        return trustStore;
    }

    public static KeyStore createEmptyTrustStore()
        throws KeyStoreException, CertificateException, IOException, NoSuchAlgorithmException {
            KeyStore trustStore = KeyStore.getInstance(KeyStore.getDefaultType());
            trustStore.load(null, null);
            return trustStore;
    }

    public static X509Certificate loadDefaultTestCert(JWSAlgorithm.Family pubKeyAlgorithm)
        throws CertificateException {

        String certPem;
        if (pubKeyAlgorithm.equals(SID_PUBLIC_KEY_ALGORITHM)) {
            certPem = TEST_RSA_CERT_PEM;
        } else if (pubKeyAlgorithm.equals(MID_PUBLIC_KEY_ALGORITHM)) {
            certPem = TEST_ECDSA_CERT_PEM;
        } else {
            throw new CertificateException("Not supported public key algorithm " + pubKeyAlgorithm);
        }

        return X509CertUtils.parse(certPem);
    }

    public static X509Certificate loadDefaultTestCert(JWSAlgorithm algorithm)
            throws CertificateException {

        if (TEST_MLDSA_ALGORITHM.equals(algorithm)) {
            return X509CertUtils.parse(TEST_MLDSA_CERT_PEM);
        }

        throw new CertificateException("Not supported JWS algorithm " + algorithm);
    }

    public static X509Certificate loadTestCert(String certPem) {
        return X509CertUtils.parse(certPem);
    }

    public static String generateTestAuthTicketWithRsaKey(
        String semanticsIdentifier,
        String serverUrl,
        String shareId,
        String nonce
    ) throws CertificateException, JOSEException, ParseException {
        return generateTestAuthTicket(
            semanticsIdentifier,
            serverUrl,
            shareId,
            nonce,
            SID_PUBLIC_KEY_ALGORITHM,
            TEST_RSA_CERT_PEM
            );
    }

    public static String generateTestAuthTicketWithEcdsaKey(
        String semanticsIdentifier,
        String serverUrl,
        String shareId,
        String nonce
    ) throws CertificateException, JOSEException, ParseException {
        return generateTestAuthTicket(
            semanticsIdentifier,
            serverUrl,
            shareId,
            nonce,
            MID_PUBLIC_KEY_ALGORITHM,
            TEST_ECDSA_CERT_PEM
        );
    }

    public static String generateTestAuthTicketWithMldsaKey(
            String semanticsIdentifier,
            String serverUrl,
            String shareId,
            String nonce
    ) throws CertificateException, JOSEException, ParseException {
        return generateTestAuthTicketWithMldsa(
                semanticsIdentifier,
                serverUrl,
                shareId,
                nonce,
                TEST_MLDSA_CERT_PEM
        );
    }

    private static String generateTestAuthTicketWithMldsa(
            String semanticsIdentifier,
            String serverUrl,
            String shareId,
            String nonce,
            String certificate
    ) throws CertificateException, JOSEException, ParseException {

        X509Certificate cert = X509CertUtils.parseWithException(certificate);
        String testSemanticsIdentifier = SIDCertificateUtil.getSemanticsIdentifier(cert);
        EtsiIdentifier etsi = new EtsiIdentifier("etsi/" + testSemanticsIdentifier);

        assertTrue(etsi.getSemanticsIdentifier().equals(semanticsIdentifier),
                "Only " + testSemanticsIdentifier + " is supported for auth ticket generation");

        AuthTokenCreator token = AuthTokenCreator.builder()
                .withEtsiIdentifier(etsi)
                .withShareAccessData(new ShareAccessData(
                        serverUrl,
                        shareId,
                        nonce))
                .withShareAccessData(new ShareAccessData(
                        "https://ccs.another-organization.org:443",
                        "5BAE4603-C33C-4425-B301-125F2ACF9B1E",
                        "9d23660840b427f405009d970d269770417bc769"))
                .build();

        signAuthTokenWithMldsa(token);

        return token.createTicketForShareId(shareId);
    }

    /**
     * Generate Auth ticket with TestData.TEST_RSAKEY.
     * @param semanticsIdentifier example PNOEE-30303039914
     * @param serverUrl server URL
     * @param shareId share ID
     * @param nonce nonce
     * @param pubKeyAlgorithm public key algorithm
     * @param certificate certificate
     * @return authentication ticket
     */
    private static String generateTestAuthTicket(
        String semanticsIdentifier,
        String serverUrl,
        String shareId,
        String nonce,
        JWSAlgorithm.Family pubKeyAlgorithm,
        String certificate
    ) throws CertificateException, JOSEException, ParseException {

        X509Certificate cert = X509CertUtils.parseWithException(certificate);
        String testSemanticsIdentifier = SIDCertificateUtil.getSemanticsIdentifier(cert); //PNOEE-30303039914
        EtsiIdentifier etsi = new EtsiIdentifier("etsi/" + testSemanticsIdentifier);

        assertTrue(etsi.getSemanticsIdentifier().equals(semanticsIdentifier),
            "Only " + testSemanticsIdentifier + " is supported for auth ticket generation");

        AuthTokenCreator token = AuthTokenCreator.builder()
            .withEtsiIdentifier(etsi) // "iss" field etsi/PNOEE-30303039914
            .withShareAccessData(new ShareAccessData(
                serverUrl,
                shareId,
                nonce))
            .withShareAccessData(new ShareAccessData(
                "https://ccs.another-organization.org:443",
                "5BAE4603-C33C-4425-B301-125F2ACF9B1E",
                "9d23660840b427f405009d970d269770417bc769"))
            .build();


        signAuthToken(token, pubKeyAlgorithm);

        return token.createTicketForShareId(shareId);
    }

    private static void signAuthToken(AuthTokenCreator token,  JWSAlgorithm.Family pubKeyAlgorithm)
        throws JOSEException, CertificateException, ParseException {

        if (pubKeyAlgorithm.equals(SID_PUBLIC_KEY_ALGORITHM)) {
            JWK jwk = JWK.parseFromPEMEncodedObjects(TEST_RSAKEY);
            RSAKey privateKey = jwk.toRSAKey();
            RSASSASigner jwsSigner = new RSASSASigner(privateKey) {
                // Smart-ID JWSSigner supports only RS256
                @Override
                public Set<JWSAlgorithm> supportedJWSAlgorithms() {
                    return Set.of(JWSAlgorithm.RS256);
                }
            };
            token.sign(jwsSigner);
            return;
        } else if (pubKeyAlgorithm.equals(MID_PUBLIC_KEY_ALGORITHM)) {
            JWK jwk = JWK.parseFromPEMEncodedObjects(TEST_ECDSA_KEY);
            ECKey privateKey = jwk.toECKey();
            ECDSASigner jwsSigner = new ECDSASigner(privateKey);
            token.sign(jwsSigner, JWSAlgorithm.ES256);
            return;
        }

        throw new CertificateException("Not supported public key algorithm " + pubKeyAlgorithm);
    }

    private static void signAuthTokenWithMldsa(AuthTokenCreator token)
            throws JOSEException, CertificateException, ParseException {

        try {
            Security.addProvider(new BouncyCastleProvider());

            String normalizedPem = TEST_MLDSA_KEY
                    .strip()
                    .replace("\r\n", "\n");

            PEMParser pemParser = new PEMParser(new StringReader(normalizedPem));
            Object parsed = pemParser.readObject();
            pemParser.close();

            if (parsed == null) {
                throw new CertificateException("Failed to parse ML-DSA PEM private key: PEMParser returned null");
            }

            JcaPEMKeyConverter converter = new JcaPEMKeyConverter().setProvider("BC");
            final java.security.PrivateKey privateKey;

            if (parsed instanceof PEMKeyPair pemKeyPair) {
                privateKey = converter.getPrivateKey(pemKeyPair.getPrivateKeyInfo());
            } else if (parsed instanceof PrivateKeyInfo privateKeyInfo) {
                privateKey = converter.getPrivateKey(privateKeyInfo);
            } else {
                throw new CertificateException("Unsupported ML-DSA PEM object: " + parsed);
            }

            com.nimbusds.jose.JWSSigner jwsSigner = new com.nimbusds.jose.JWSSigner() {
                private final JCAContext jcaContext = new JCAContext();

                @Override
                public Base64URL sign(JWSHeader header, byte[] signingInput) throws JOSEException {
                    if (!supportedJWSAlgorithms().contains(header.getAlgorithm())) {
                        throw new JOSEException("Unsupported JWS algorithm: " + header.getAlgorithm());
                    }

                    try {
                        Signature signer = Signature.getInstance("MLDSA", "BC");
                        signer.initSign(privateKey);
                        signer.update(signingInput);
                        return Base64URL.encode(signer.sign());
                    } catch (Exception e) {
                        throw new JOSEException("ML-DSA signing failed", e);
                    }
                }

                @Override
                public Set<JWSAlgorithm> supportedJWSAlgorithms() {
                    return Set.of(TEST_MLDSA_ALGORITHM);
                }

                @Override
                public JCAContext getJCAContext() {
                    return jcaContext;
                }
            };

            token.sign(jwsSigner, TEST_MLDSA_ALGORITHM);

        } catch (IOException e) {
            throw new CertificateException("Failed to parse ML-DSA private key PEM", e);
        }
    }
}
